# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Provides a complete interface to CSV files and data
gem "csv", "~> 3.2", ">= 3.2.8"
# Converts objects into their Hash representations
gem "ishin", "~> 0.4.0"
# JSON implementation as a Ruby extension in C
gem "json", "~> 2.7", ">= 2.7.1"
# Makes it easy and painless to work with XML and HTML
gem "nokogiri", "~> 1.16", ">= 1.16.3"
# Lets decompose inline CSS styling in HTML
gem "nokogiri-styles", "~> 0.1.0"
# Parse YAML safely
gem "safe_yaml", "~> 1.0", ">= 1.0.5"
